# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: HealthByte-Lambda-Events
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: java8

# you can overwrite defaults here
#  stage: dev  
  region: ap-south-1
iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"

package:
  artifact: target/LambdaEvents-1.0.jar

functions:
  presignUploadURL:
    handler: service.App::getPresignedUrl
  getSleepData:
    handler: service.App::getSleepData
  getAllUserData:
    handler: service.App::getAllUserData
  downloadResource:
    handler: service.App::handleRequest
  getUserData:
    handler: service.App::getUserData
  addUser:
    handler: service.App::addUser
  addSleepDataAnlysis:
    handler: service.App::addSleepDataAnlysis
  getSleepDataAnalysis:
    handler: service.App::getSleepDataAnalysis

# you can add CloudFormation resource templates here
plugins:
  - serverless-plugin-warmup
